# Generated by Django 5.1.1 on 2024-09-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_staticassets_options_alter_staticassets_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('preview', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Open Source',
                'verbose_name_plural': 'Open Source',
            },
        ),
    ]
