# Generated by Django 5.1.1 on 2024-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_opensource'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensource',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/opensource/'),
        ),
    ]
