# Generated by Django 5.1.1 on 2024-09-22 10:05

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_opensource_video_alter_opensource_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensource',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=resume.models.opensourse_img_destination),
        ),
        migrations.AlterField(
            model_name='opensource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=resume.models.opensourse_video_destination),
        ),
    ]
