# Generated by Django 5.1.1 on 2024-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_opensource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competitive Programming',
                'verbose_name_plural': 'Competitive Programming',
            },
        ),
    ]
