# Generated by Django 5.1.1 on 2024-09-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_competitive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitive',
            name='number',
        ),
    ]
