# Generated by Django 5.1.1 on 2024-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
