# Generated by Django 5.1.1 on 2024-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
