# Generated by Django 5.1.1 on 2024-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_education_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('url', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
