# Generated by Django 5.1.1 on 2024-09-23 12:11

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, null=True)),
                ('tag1', models.CharField(blank=True, null=True)),
                ('tag2', models.TextField(blank=True, null=True)),
                ('tag3', models.CharField(blank=True, null=True)),
                ('tag4', models.IntegerField(blank=True, null=True)),
                ('tag5', models.BooleanField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=resume.models.extra_file_destination)),
                ('tag6', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extra',
            },
        ),
    ]
